### PR TITLE
fix: Hide capabilities section when no capabilities are defined.

### LINKED ISSUE #901: Don't render "Capabilities" section for loader plugins that don't define capabilities
Many loaders have no capabilities defined. In those cases, we currently render the normal summary/disclaimer text about capabilities but then have no capabilities listed below it. This can be confusing and should be removed.

### PR DESCRIPTION
**Pull request by cjohnhanson**
Closes #901

### CODE REVIEW

File: src/components/PluginCapabilitiesSection.vue [hunk 1]
```diff
@@ -1,7 +1,7 @@
 <template>
   <div>
     <p class="text-3xl py-4" id="capabilities">Capabilities</p>
-    <span class="space-y-3" v-if="capabilities">
+    <span class="space-y-3" v-if="len(capabilities) > 0">
```
Comment (tayloramurphy) [inline src/components/PluginCapabilitiesSection.vue:4]:
```suggestion
    <span class="space-y-3" v-if="capabilities && capabilities.length">
```

Based on how settings is done I think this is the way?

**Review by tayloramurphy — APPROVED** [review]

**Comment by tayloramurphy** [comment]
Looks good on https://deploy-preview-904--meltano-hub.netlify.app/transformers/dbt-bigquery vs https://hub.meltano.com/transformers/dbt-bigquery/

**Review by edgarrmondragon — APPROVED** [review]
lgtm :shipit:
